In [1]:
import numpy as np

## Question 1

In [2]:
A = np.array([[4,3],[6,9]])
print 'A=' +str(A)

B = np.array([[-2,9],[-5,2]])
print 'B=' + str(B)

A=[[4 3]
 [6 9]]
B=[[-2  9]
 [-5  2]]


In [3]:
print A-B

[[ 6 -6]
 [11  7]]


## Question 2

In [4]:
x = np.array([[2],[7],[4],[1]])
print x

[[2]
 [7]
 [4]
 [1]]


In [20]:
np.multiply(0.5,x)

array([[1. ],
       [3.5],
       [2. ],
       [0.5]])

## Question 3

In [6]:
u = np.array([[8],[1],[4]])
print u

[[8]
 [1]
 [4]]


In [11]:
np.transpose(u)

array([[ 1,  3, -1]])

## Question 4

In [12]:
u = np.array([[1],[3],[-1]])
v = np.array([[2],[2],[4]])
t = np.transpose(u)
np.matmul(t,v)

array([[4]])

## Question 5
Let A and B be 3X3 (square) matrices. 
a. A*B = B*A

b. If B is a 3X3 identity matrix, then A*B = B*A

c. (A*B)*A = A*(B*A)

d. If C = A*B, then C is a 6*\6 matrix.

In [13]:
answer = raw_input('Which of the following must necessarily hold true? ')
print 'Answer is ' + str(answer)

Which of the following must necessarily hold true? b. and c.
Answer is b. and c.
